#INCLUDE <P16F877.INC>

	SAYAC	EQU		0X21;TÝMER1 KESME ARALIÐINI ARTTIRMAK ÝÇÝN SAYAÇ OLUÞTURULDU
	INTX 	EQU		0X22;TÝMER0 KESME ARALIÐINI ARTTIRMAK ÝÇÝN SAYAÇ OLUÞTURULDU
	ORG 	0X00		;BAÞLANGIÇ VEKTÖRÜNÜN ADRESÝ
	GOTO	START		;START ETÝKETÝNE DALLANACAK
	ORG 	0X04		;KESME VEKTÖRÜNÜN ADRESÝ
	GOTO 	KESME		;KESME OLUNCA KESME ETÝKETÝNE DALLANACAK
START
	MOVLW 	B'11000000' ;TÝMER0 ÝÇÝN INTCON REGÝSTERINA GEREKLÝ OLAN
	MOVWF 	INTCON		;DEÐERLER YERLEÞTÝRÝLÝYOR
	BSF		STATUS,RP0	;BANK1 E GEÇME ÝÞLEMÝ
	BSF		PIE1,0		;TÝMER1 ÝÇÝN PIE1 REGÝSTERININ 0. BÝTÝ ENABLE EDÝLÝYOR
	BANKSEL	TRISB		;TRISB REGÝSTERININ OLDUÐU BANK'A GEÇÝLÝYOR
	CLRF	TRISB       ;TRISB MANTIKSAL OLARAK ÇIKIÞ YAPILIYOR
	CLRF	TRISD		;TRISD MANTIKSAL OLARAK ÇIKIÞ YAPILIYOR
	BCF		STATUS,RP0	;BANK0 A GEÇÝLÝYOR
	MOVLW   B'00010001' ;TÝMER1 ÝÇÝN T1CON REGÝSTERINA                       
	MOVWF 	T1CON		;GEREKLÝ DEÐERLER YERLEÞTÝRÝLÝYOR
	MOVLW 	D'1'		;TÝMER1 ÝÇÝN
	MOVWF 	SAYAC		;SAYAC DEÐÝÞKENÝNE DEÐER ATANIYOR
	
	MOVLW	0X01		;PORTB REGÝSTERINA 
	MOVWF	PORTB		;1 DEÐERÝ ATANIYOR
	MOVLW	0X01		;PORTD REGÝSTERINA 
	MOVWF	PORTD		;1 DEÐERÝ ATANIYOR

	MOVLW	D'250'		;TÝMER0 ÝÇÝN INTX DEÐÝÞKENÝNE  
	MOVWF	INTX		;DEÐER ATANIYOR
	BANKSEL	OPTION_REG	;OPTION_REG'IN OLDUÐU BANK'A GEÇÝÞ ÝÞLEMÝ
	MOVLW	B'11010001'	;TÝMER0 ÝÇÝN OPTION_REG 
	MOVWF	OPTION_REG	;REGÝSTERINA DEÐER ATANIYOR

	BANKSEL	TMR0		;TMR0'IN OLDUÐU BANK'A GEÇÝÞ ÝÞLEMÝ
	MOVLW	D'6'		;TÝMER0 ÝÇÝN TMR0 DEÐÝÞKENÝNE
	MOVWF	TMR0		;6 DEÐERÝ ATANIYOR
	BANKSEL	INTCON		;INTCON REGÝSTERININ OLDUÐU BANK'A GEÇÝÞ
	BSF		INTCON,D'5'	;INTCON REGÝSTERININ 5.BÝTÝ SET EDÝLÝYOR
	BSF		INTCON,D'7'	;INTCON REGÝSTERININ 7.BÝTÝ SET EDÝLÝYOR
	MOVLW 	H'15'		;TÝMER1 ÝÇÝN TMR1H DEÐÝÞKENÝNE 
	MOVWF 	TMR1H		;0X15 DEÐERÝ ATANIYOR
	MOVLW 	H'A0'		;TÝMER1 ÝÇÝN TMR1L DEÐÝÞKENÝNE 
	MOVWF 	TMR1L		;0XA0 DEÐERÝ ATANIYOR
	GOTO	DON			;DON ETÝKETÝNE DALLANILIYOR
KESME
	BTFSS	INTCON,2	;TÝMER0 ÝÇÝN INTCON 2.BÝTÝ KONTROL EDÝLÝYOR
	GOTO	$+4			;4 SATIR AÞAÐI DALLANILIYOR
	DECFSZ 	INTX,1		;INTX DEÐÝÞKENÝ BÝR AZALTILIP 0 MI DEÐÝL MÝ KONTROL EDÝLÝYOR
	GOTO	TMR0_DENE	;TMR0_DENE ETÝKETÝNE DALLANILIYOR
	CALL	PORTB_YAK	;PORTB_YAK ETÝKETÝNE DALLANILIYOR
	BTFSS	PIR1,0		;TÝMER1 ÝÇÝN PIR1 DEÐÝÞKENÝNÝN 0. BÝTÝNÝN 1 OLUP OLMADIÐI KONTROL EDÝLÝYOR
	RETFIE				;KESMEYE DÖNÜÞ
	DECFSZ	SAYAC,1		;SAYAC DEÐÝÞKENÝ BÝR AZALTILIP 0 MI DEÐÝL MÝ KONTROL EDÝLÝYOR
	GOTO	DENE		;DENE ETÝKETÝNE DALLANILIYOR
	GOTO	YAK			;YAK ETÝKETÝNE DALLANILIYOR
TMR0_DENE
	MOVLW	D'6'		;TÝMER0 ÝÇÝN TMR0 DEÐÝÞKENÝNE
	MOVWF	TMR0		;6 DEÐERÝ ATANIYOR
	BCF		INTCON,2	;TÝMER0 ÝÇÝN FLAG DÝSABLE EDÝLÝYOR
	RETFIE				;KESMEYE DÖNÜÞ
PORTB_YAK	
	BANKSEL	PORTB		;PORTB'NIN OLDUÐU BANK'A GEÇÝÞ ÝÞLEMÝ
	RLF		PORTB		;PORTB ÝÇERÝÐÝ BÝR KERE SOLA KAYDIRILIYOR
	MOVLW	D'6'		;TÝMER0 ÝÇÝN TMR0 DEÐÝÞKENÝNE
	MOVWF	TMR0		;6 DEÐERÝ ATANIYOR
	MOVLW	D'250'		;TÝMER0 ÝÇÝN INTX DEÐÝÞKENÝNE  
	MOVWF	INTX		;DEÐER ATANIYOR
	BCF		INTCON,2	;TÝMER0 ÝÇÝN FLAG DÝSABLE EDÝLÝYOR
	RETURN
DENE
	BANKSEL	PIR1		;PIR1 REGÝSTERINI OLDUÐU BANK'A GEÇÝÞ ÝÞLEMÝ
	BCF	  	PIR1,0		;TÝMER1 ÝÇÝN PIR1 FLAG REGÝSTERI DÝSABLE EDÝLÝYOR
	MOVLW 	H'15'		;TÝMER1 ÝÇÝN TMR1H DEÐÝÞKENÝNE
	MOVWF 	TMR1H		;0X15 DEÐERÝ ATANIYOR
	MOVLW 	H'A0'		;TÝMER1 ÝÇÝN TMR1L DEÐÝÞKENÝNE 
	MOVWF 	TMR1L		;0XA0 DEÐERÝ ATANIYOR
	RETFIE				;KESMEYE DÖNÜÞ
YAK	
	BANKSEL	PIR1		;PIR1 REGÝSTERINI OLDUÐU BANK'A GEÇÝÞ ÝÞLEMÝ
	BCF	  	PIR1,0		;TÝMER1 ÝÇÝN PIR1 FLAG REGÝSTERI DÝSABLE EDÝLÝYOR
	RRF		PORTD		;PORTD DEÐÝÞKENÝN ÝÇERÝÐÝ BÝR SAÐA KAYDIRILIYOR
	MOVLW 	H'15'		;TÝMER1 ÝÇÝN TMR1H DEÐÝÞKENÝNE
	MOVWF 	TMR1H		;0X15 DEÐERÝ ATANIYOR
	MOVLW 	H'A0'		;TÝMER1 ÝÇÝN TMR1L DEÐÝÞKENÝNE 
	MOVWF 	TMR1L		;0XA0 DEÐERÝ ATANIYOR
	MOVLW	D'1'		;TÝMER1 ÝÇÝN SAYAC 
	MOVWF	SAYAC		;DEÐÝÞKENÝNE 1 DEÐERÝ ATANIYOR
	RETFIE				;KESMEYE DÖNÜÞ
DON
	GOTO	DON			;DON ETÝKETÝNE DALLANILIYOR
END