#INCLUDE <P16F877.INC>
ADC_DATA	EQU		0X21
YBOLUM		EQU		0X24
OBOLUM		EQU		0X25
YUZLER		EQU		0X26
ONLAR		EQU		0X27
BIRLER		EQU		0X28

	ORG	0X00

	MOVLW	D'125'
	MOVWF	ADC_DATA
YUZLER_KONT
	MOVLW	0X0A
	SUBWF	ADC_DATA,W
	BTFSS	STATUS,C
	GOTO	ONLAR_KONT
	INCF	YBOLUM,F
	MOVLW	0X0A
	SUBWF	ADC_DATA,F
	GOTO	YUZLER_KONT
ONLAR_KONT
	MOVF	ADC_DATA,W
	MOVWF	YUZLER
	MOVLW	0X0A
	SUBWF	YBOLUM,W
	BTFSS	STATUS,C
	GOTO	BIRLER_KONT
	INCF	OBOLUM,F
	MOVLW	0X0A
	SUBWF	YBOLUM,F
	GOTO	ONLAR_KONT
BIRLER_KONT
	MOVF	YBOLUM,W
	MOVWF	ONLAR
	MOVF	OBOLUM,W
	MOVWF	BIRLER
END