# MPLAB IDE generated this makefile for use with GNU make.
# Project: Sýnav.mcp
# Date: Thu May 19 23:37:26 2011

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

Sýnav.cof : Untitled.o
	$(CC) /p16F877 "Untitled.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Sýnav.cof" /M"Sýnav.map" /W

Untitled.o : Untitled.asm C:/Program\ Files/Microchip/MPASM\ Suite/p16F877.inc
	$(AS) /q /p16F877 "Untitled.asm" /l"Untitled.lst" /e"Untitled.err" /o"Untitled.o" /d__DEBUG=1

clean : 
	$(CC) "Untitled.o" "Untitled.err" "Untitled.lst" "Sýnav.cof" "Sýnav.hex"

