# MPLAB IDE generated this makefile for use with GNU make.
# Project: ödev3.mcp
# Date: Tue Nov 09 15:38:35 2010

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

ödev3.cof : ödev3.o
	$(CC) /p16F877 "ödev3.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"ödev3.cof" /M"ödev3.map" /W

ödev3.o : ödev3.asm C:/Program\ Files/Microchip/MPASM\ Suite/p16F877.inc
	$(AS) /q /p16F877 "ödev3.asm" /l"ödev3.lst" /e"ödev3.err" /o"ödev3.o" /d__DEBUG=1

clean : 
	$(CC) "ödev3.o" "ödev3.err" "ödev3.lst" "ödev3.cof" "ödev3.hex"

