# MPLAB IDE generated this makefile for use with GNU make.
# Project: Ödev4.mcp
# Date: Mon Dec 27 14:22:30 2010

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

Ödev4.cof : Ödev4.o
	$(CC) /p16F877 "Ödev4.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Ödev4.cof" /M"Ödev4.map" /W

Ödev4.o : Ödev4.asm C:/Program\ Files/Microchip/MPASM\ Suite/P16F877A.inc
	$(AS) /q /p16F877 "Ödev4.asm" /l"Ödev4.lst" /e"Ödev4.err" /o"Ödev4.o" /d__DEBUG=1

clean : 
	$(CC) "Ödev4.o" "Ödev4.err" "Ödev4.lst" "Ödev4.cof" "Ödev4.hex"

